### PR TITLE
created booking, user, and pokemon model

### PR DESCRIPTION
**Pull request by Version-LAA**
Created the following models - see schema images below:
- User (using devise) - We still need to do a separate migration for the remaining fields such as name.
- Pokemon
- Booking
Screen Shot 2023-04-27 at 9 41 22 PM

Screen Shot 2023-04-27 at 9 41 30 PM

### CODE REVIEW

**Review by Kameronjan — COMMENTED** [review]
Looks great!

**Review by btukov — APPROVED** [review]

**Comment by Kameronjan** [comment]
Looks good!

**Review by mccdesign — APPROVED** [review]
Looks great!

**Review by Kameronjan — APPROVED** [review]
Third review, gtg!

**Pull request merged**
